"""项目内资源文件名与 Blender 对象名。"""

from __future__ import annotations

DEFAULT_HEAD_OBJECT_NAME = "Head"
SRANIPAL_EYE_LEFT_OBJECT_NAME = "Eye_Left"
SRANIPAL_EYE_RIGHT_OBJECT_NAME = "Eye_Right"

METAHUMAN_HEAD_OBJECT_NAME = "head_lod0_ORIGINAL"
METAHUMAN_TEETH_OBJECT_NAME = "teeth_ORIGINAL"
METAHUMAN_EYE_LEFT_OBJECT_NAME = "eyeLeft_ORIGINAL"
METAHUMAN_EYE_RIGHT_OBJECT_NAME = "eyeRight_ORIGINAL"
METAHUMAN_FBX = "Metahuman_Head.fbx"
