"""播放与 Open3D 预览的默认参数。"""

from __future__ import annotations

DEFAULT_PLAYBACK_FPS = 30.0
DEFAULT_OPEN3D_WINDOW_NAME = "Face Blender Shape Viewer"
DEFAULT_OPEN3D_WIDTH = 1280
DEFAULT_OPEN3D_HEIGHT = 900
DEFAULT_OPEN3D_BACKGROUND_RGB = (0.86, 0.89, 0.93)
DEFAULT_OPEN3D_VERTEX_MATTE_GAMMA = 1.14
DEFAULT_OPEN3D_BAKED_SHADING = False
DEFAULT_OPEN3D_BAKED_AMBIENT = 0.24
DEFAULT_OPEN3D_BAKED_DIFFUSE = 0.78
DEFAULT_OPEN3D_SKIN_DETAIL_ENABLED = True
DEFAULT_OPEN3D_SKIN_CREASE_STRENGTH = 0.45
DEFAULT_OPEN3D_SKIN_MICRO_STRENGTH = 0.085
DEFAULT_OPEN3D_SKIN_MICRO_FREQ = 95.0
DEFAULT_VIEW_SCALE = 2.2
DEFAULT_OPEN3D_VISUAL_PRESET = "neutral_bust"
