"""open3d.visualization 占位存根。"""

from typing import Any

class ViewControl:
    def set_lookat(self, lookat: Any) -> None: ...
    def set_front(self, front: Any) -> None: ...
    def set_up(self, up: Any) -> None: ...
    def set_zoom(self, zoom: float) -> None: ...

class RenderOption:
    line_width: float

class Visualizer:
    def create_window(
        self,
        window_name: str = ...,
        width: int = ...,
        height: int = ...,
        left: int = ...,
        top: int = ...,
        visible: bool = ...,
    ) -> bool: ...
    def add_geometry(self, geometry: Any, reset_bounding_box: bool = ...) -> bool: ...
    def update_geometry(self, geometry: Any) -> bool: ...
    def get_view_control(self) -> ViewControl: ...
    def get_render_option(self) -> RenderOption: ...
    def poll_events(self) -> None: ...
    def update_renderer(self) -> None: ...
